# Generated by Django 2.1.5 on 2019-02-07 10:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_indicators_strategy'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategy',
            name='alloted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='strategy',
            name='task_id',
            field=models.CharField(default='', max_length=100),
        ),
    ]
