# Generated by Django 2.1.5 on 2019-02-12 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190207_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicators',
            name='value',
            field=models.FloatField(null=True),
        ),
    ]
