# Generated by Django 2.1.5 on 2019-02-12 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20190212_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicators',
            name='value',
            field=models.CharField(default='0.0', max_length=20),
        ),
    ]
