# Generated by Django 2.1.5 on 2019-02-12 09:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20190212_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicators',
            name='updated_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
