# Generated by Django 2.1.5 on 2019-02-13 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_indicators_updated_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Indicators',
        ),
    ]
