# Generated by Django 2.1.5 on 2019-02-13 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_delete_indicators'),
    ]

    operations = [
        migrations.CreateModel(
            name='refresh_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(default='False', max_length=100)),
            ],
        ),
    ]
