# Generated by Django 2.1.5 on 2019-02-13 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_refresh_data'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='refresh_data',
            new_name='Refreshed',
        ),
    ]
