# Generated by Django 2.1.5 on 2019-02-15 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_indicator'),
    ]

    operations = [
        migrations.CreateModel(
            name='Moving_Average',
            fields=[
                ('indicator_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blog.Indicator')),
                ('ma_type', models.CharField(default='price', max_length=100)),
                ('period', models.CharField(default='20', max_length=100)),
                ('interval', models.CharField(default='minute', max_length=100)),
            ],
            bases=('blog.indicator',),
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('indicator_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blog.Indicator')),
            ],
            bases=('blog.indicator',),
        ),
        migrations.CreateModel(
            name='Volume',
            fields=[
                ('indicator_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blog.Indicator')),
            ],
            bases=('blog.indicator',),
        ),
    ]
