# Generated by Django 2.1.5 on 2019-02-15 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_moving_average_price_volume'),
    ]

    operations = [
        migrations.CreateModel(
            name='Example',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ref', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='blog.Indicator')),
            ],
        ),
    ]
