# Generated by Django 2.1.5 on 2019-02-19 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_example'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='strategy',
            name='indicator1',
        ),
        migrations.RemoveField(
            model_name='strategy',
            name='indicator2',
        ),
        migrations.AlterField(
            model_name='example',
            name='ref',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='blog.Indicator'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
