# Generated by Django 2.1.5 on 2019-02-19 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_auto_20190219_1545'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='example',
            name='ref',
        ),
        migrations.DeleteModel(
            name='Example',
        ),
    ]
