# Generated by Django 2.1.5 on 2019-02-19 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_auto_20190219_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategy',
            name='indicator1',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='indicator1', to='blog.Indicator'),
        ),
        migrations.AddField(
            model_name='strategy',
            name='indicator2',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='indicator2', to='blog.Indicator'),
        ),
    ]
