# Generated by Django 2.1.5 on 2019-03-04 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_auto_20190228_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='chaikin_volatility',
            name='rate_of_change',
            field=models.CharField(default='10', max_length=100),
        ),
    ]
