# Generated by Django 2.1.5 on 2019-03-05 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_chaikin_volatility_rate_of_change'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chaikin_volatility',
            name='rate_of_change',
            field=models.CharField(default='2', max_length=100),
        ),
        migrations.AlterField(
            model_name='moving_average',
            name='period',
            field=models.CharField(default='10', max_length=100),
        ),
    ]
