# Generated by Django 2.1.5 on 2019-03-15 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0029_strategy_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategy_group',
            name='display',
            field=models.CharField(default='NONE', max_length=200),
        ),
    ]
